### ISSUE TITLE
Plume velocity settings not accessible when no optical flow is set on start-up

### ISSUE THREAD

**Issue by twVolc** [twVolc/PyCamPermanent#68]
If all of `flow_raw`, `flow_histo` and `flow_hybrid` are set to 0 (i.e. not to be used) in the config file, the Plume velocity settings frame doesn't load properly - presumably because some processing hasn't occurred on start-up that typically would be performed if any of those settings are set to 1.

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\gg1tcw\AppData\Local\anaconda3\envs\pycam\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\gg1tcw\Documents\Python Scripts\PyCamPermanent\pycam\gui\figures_analysis.py", line 4835, in generate_frame
    self._build_fig_vel()
  File "C:\Users\gg1tcw\Documents\Python Scripts\PyCamPermanent\pycam\gui\figures_analysis.py", line 5206, in _build_fig_vel
    self.img_vel = self.pyplis_worker.velo_img
AttributeError: 'PyplisWorker' object has no attribute 'velo_img'
```

**Comment by twVolc** [comment]
Recent commit fixes this so I'll close it now even though it's not yet merged with master
